/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ControllerCadastro;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author sitta
 */
public class CadastroFrame extends javax.swing.JFrame {

    /**
     * Creates new form CadastroFrame
     */
    public CadastroFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Entrada_nome = new javax.swing.JTextField();
        lblEntrada_nome = new javax.swing.JLabel();
        lblEntrada_usuario = new javax.swing.JLabel();
        Entrada_usuario = new javax.swing.JTextField();
        Entrada_senha = new javax.swing.JTextField();
        lblEntrada_senha = new javax.swing.JLabel();
        Bcadastro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblEntrada_nome.setText("Nome:");

        lblEntrada_usuario.setText("Usuario:");

        Entrada_senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Entrada_senhaActionPerformed(evt);
            }
        });

        lblEntrada_senha.setText("Senha:");

        Bcadastro.setText("Cadastrar");
        Bcadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcadastroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblEntrada_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(lblEntrada_nome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblEntrada_senha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Entrada_senha, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                            .addComponent(Entrada_nome)
                            .addComponent(Entrada_usuario)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(Bcadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Entrada_nome, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(lblEntrada_nome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEntrada_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Entrada_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Entrada_senha, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(lblEntrada_senha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(54, 54, 54)
                .addComponent(Bcadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public JButton getBcadastro() {
        return Bcadastro;
    }

    public void setBcadastro(JButton Bcadastro) {
        this.Bcadastro = Bcadastro;
    }

    public JTextField getEntrada_nome() {
        return Entrada_nome;
    }

    public void setEntrada_nome(JTextField Entrada_nome) {
        this.Entrada_nome = Entrada_nome;
    }

    public JTextField getEntrada_senha() {
        return Entrada_senha;
    }

    public void setEntrada_senha(JTextField Entrada_senha) {
        this.Entrada_senha = Entrada_senha;
    }

    public JTextField getEntrada_usuario() {
        return Entrada_usuario;
    }

    public void setEntrada_usuario(JTextField Entrada_usuario) {
        this.Entrada_usuario = Entrada_usuario;
    }

    public JLabel getLblEntrada_nome() {
        return lblEntrada_nome;
    }

    public void setLblEntrada_nome(JLabel lblEntrada_nome) {
        this.lblEntrada_nome = lblEntrada_nome;
    }

    public JLabel getLblEntrada_senha() {
        return lblEntrada_senha;
    }

    public void setLblEntrada_senha(JLabel lblEntrada_senha) {
        this.lblEntrada_senha = lblEntrada_senha;
    }

    public JLabel getLblEntrada_usuario() {
        return lblEntrada_usuario;
    }

    public void setLblEntrada_usuario(JLabel lblEntrada_usuario) {
        this.lblEntrada_usuario = lblEntrada_usuario;
    }
    
    private void Entrada_senhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Entrada_senhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Entrada_senhaActionPerformed

    private void BcadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BcadastroActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(CadastroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(CadastroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(CadastroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(CadastroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new CadastroFrame().setVisible(true);
//            }
//        });
//    }
    private ControllerCadastro controller;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bcadastro;
    private javax.swing.JTextField Entrada_nome;
    private javax.swing.JTextField Entrada_senha;
    private javax.swing.JTextField Entrada_usuario;
    private javax.swing.JLabel lblEntrada_nome;
    private javax.swing.JLabel lblEntrada_senha;
    private javax.swing.JLabel lblEntrada_usuario;
    // End of variables declaration//GEN-END:variables
}
